name: Publish
on:
  push:
    tags:
      - '*'
jobs:
  publish:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Setup nuget source
      run: dotnet nuget add source --username bervProject --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/bervproject/index.json"
    - name: Package
      run: dotnet pack --configuration Release
    - run: dotnet nuget push "BervProject.FeatureFlag/bin/Release/BervProject.FeatureFlag.${{ github.ref_name }}.nupkg"  --source "github"
